canciones={
    "Gasolina": ["reggaeton", "2004", "puerto rico", "energico", "bailable", "Daddy Yankee", "Barrio Fino", "clasico"],
    "Dakiti": ["reggaeton", "2020", "puerto rico", "sensual", "bailable", "Bad Bunny", "Jhay Cortez", "viral"],
    "Titi Me Pregunto": ["reggaeton", "2022", "puerto rico", "divertido", "fiesta", "Bad Bunny", "Un Verano Sin Ti", "experimental"],
    "Con Calma": ["reggaeton", "2019", "puerto rico", "bailable", "familiar", "Daddy Yankee", "Snow", "fusion"],
    "Te Boté": ["reggaeton", "2018", "puerto rico", "melancolico", "desahogo", "Casper Magico", "Nio Garcia", "colaboracion"],
    "X": ["reggaeton", "2017", "colombia", "sensual", "bailable", "Nicky Jam", "J Balvin", "hit internacional"],
    "Mi Gente": ["reggaeton", "2017", "colombia", "festivo", "bailable", "J Balvin", "Willy William", "himno mundial"],
    "Sensacion Del Bloque": ["reggaeton", "2005", "puerto rico", "nostalgico", "bailable", "Daddy Yankee", "Barrio Fino", "clasico"],
    "Ella Me Levanto": ["reggaeton", "2007", "puerto rico", "energico", "bailable", "Daddy Yankee", "El Cartel", "exito"],
    "Diles": ["trap latino", "2016", "puerto rico", "oscuro", "reflexion", "Bad Bunny", "Ozuna", "inicio carrera"],
    "Vivir Mi Vida": ["salsa", "2013", "puerto rico", "alegre", "bailable", "Marc Anthony", "3.0", "positivo"],
    "Pedro Navaja": ["salsa", "1978", "panama", "narrativo", "reflexion", "Rubén Blades", "Siembra", "clasico"],
    "Quimbara": ["salsa", "1974", "cuba", "energico", "bailable", "Celia Cruz", "Celia y Johnny", "iconico"],
    "La Vida Es Un Carnaval": ["salsa", "1998", "cuba", "optimista", "consuelo", "Celia Cruz", "Mi Vida Es Cantar", "himno"],
    "El Cantante": ["salsa", "1978", "puerto rico", "dramatico", "melancolico", "Héctor Lavoe", "Comedia", "biografico"],
    "Y Hubo Alguien": ["salsa", "1996", "puerto rico", "romantico", "bailable", "Marc Anthony", "Todo a Su Tiempo", "exito"],
    "La Rebelion": ["salsa", "1986", "colombia", "protesta", "bailable", "Joe Arroyo", "Rebelion", "historico"],
    "Aguanile": ["salsa", "1975", "puerto rico", "espiritual", "bailable", "Héctor Lavoe", "La Voz", "religioso"],
    "Idilio": ["salsa", "2000", "puerto rico", "romantico", "bailable", "Willie Colón", "Idilio", "fusion"],
    "Virgen": ["salsa", "1978", "puerto rico", "nostalgico", "reflexion", "Andy Montañez", "La Cosa", "clasico"],
    "Propuesta Indecente": ["bachata", "2013", "republica dominicana", "sensual", "romantico", "Romeo Santos", "Formula Vol. 1", "exito"],
    "Darte un Beso": ["bachata", "2013", "republica dominicana", "romantico", "bailable", "Prince Royce", "Soy el Mismo", "suave"],
    "Bachata Rosa": ["bachata", "1990", "republica dominicana", "poetico", "romantico", "Juan Luis Guerra", "Bachata Rosa", "premio grammy"],
    "Estrellitas y Duendes": ["bachata", "1994", "republica dominicana", "nostalgico", "reflexion", "Juan Luis Guerra", "Fogaraté", "clasico"],
    "Yo Quiero Bailar": ["bachata", "2003", "republica dominicana", "festivo", "bailable", "Sonia Silvestre", "Bachata Rosa", "iconico"],
    "La Bachata": ["bachata", "2022", "republica dominicana", "moderno", "bailable", "Manuel Turizo", "2000", "viral"],
    "Perdido": ["bachata", "2002", "republica dominicana", "melancolico", "desahogo", "Yoskar Sarante", "Perdido", "exito"],
    "Te Espero": ["bachata", "2005", "republica dominicana", "romantico", "bailable", "Raulin Rodriguez", "Te Espero", "clasico"],
    "Voy a Beber": ["bachata", "2004", "republica dominicana", "alegre", "fiesta", "Joe Veras", "Voy a Beber", "festivo"],
    "Odio": ["bachata", "2015", "republica dominicana", "pasional", "desahogo", "Romeo Santos", "Formula Vol. 2", "colaboracion"],
    "Bad Guy": ["pop", "2019", "eeuu", "ironico", "baile", "Billie Eilish", "When We All Fall Asleep", "premio grammy"],
    "Rolling in the Deep": ["pop", "2010", "reino unido", "pasional", "desahogo", "Adele", "21", "exito mundial"],
    "Shape of You": ["pop", "2017", "reino unido", "sensual", "bailable", "Ed Sheeran", "÷", "record ventas"],
    "Uptown Funk": ["pop", "2014", "eeuu", "festivo", "fiesta", "Mark Ronson", "Bruno Mars", "retro"],
    "Blinding Lights": ["pop", "2019", "canada", "nostalgico", "conduccion", "The Weeknd", "After Hours", "synthwave"],
    "Hello": ["pop", "2015", "reino unido", "melancolico", "reflexion", "Adele", "25", "emocional"],
    "Despacito": ["pop latino", "2017", "puerto rico", "sensual", "bailable", "Luis Fonsi", "Daddy Yankee", "viral global"],
    "Havana": ["pop", "2017", "cuba", "seductor", "bailable", "Camila Cabello", "Camila", "exito"],
    "Shake It Off": ["pop", "2014", "eeuu", "alegre", "baile", "Taylor Swift", "1989", "empoderamiento"],
    "Firework": ["pop", "2010", "eeuu", "inspirador", "motivacion", "Katy Perry", "Teenage Dream", "himno"],
    "Bohemian Rhapsody": ["rock", "1975", "reino unido", "epico", "opera", "Queen", "A Night at the Opera", "clasico"],
    "Sweet Child O' Mine": ["rock", "1987", "eeuu", "nostalgico", "baile", "Guns N' Roses", "Appetite for Destruction", "iconico"],
    "Smells Like Teen Spirit": ["grunge", "1991", "eeuu", "rebelde", "fiesta", "Nirvana", "Nevermind", "himno generacional"],
    "Hotel California": ["rock", "1976", "eeuu", "misterioso", "reflexion", "Eagles", "Hotel California", "leyenda"],
    "Wonderwall": ["rock", "1995", "reino unido", "melancolico", "acustico", "Oasis", "(What's the Story) Morning Glory?", "iconico"],
    "Livin' on a Prayer": ["rock", "1986", "eeuu", "energico", "fiesta", "Bon Jovi", "Slippery When Wet", "clasico"],
    "Another Brick in the Wall": ["rock", "1979", "reino unido", "protesta", "reflexion", "Pink Floyd", "The Wall", "educativo"],
    "Enter Sandman": ["metal", "1991", "eeuu", "oscuro", "concierto", "Metallica", "Metallica", "pesado"],
    "Stairway to Heaven": ["rock", "1971", "reino unido", "epico", "reflexion", "Led Zeppelin", "Led Zeppelin IV", "masterpiece"],
    "Boulevard of Broken Dreams": ["rock alternativo", "2004", "eeuu", "melancolico", "soledad", "Green Day", "American Idiot", "emo"],
    "Chanel": ["trap latino", "2017", "puerto rico", "sofisticado", "reflexion", "Bad Bunny", "X100PRE", "experimental"],
    "No Me Conoce": ["trap latino", "2019", "puerto rico", "oscuro", "bailable", "Jhay Cortez", "Famouz", "remix"],
    "Safaera": ["reggaeton", "2020", "puerto rico", "caotico", "fiesta", "Bad Bunny", "YHLQMDLG", "experimental"],
    "La Bicicleta": ["vallenato", "2016", "colombia", "alegre", "bailable", "Carlos Vives", "Shakira", "fusion"],
    "Ginza": ["reggaeton", "2015", "puerto rico", "sensual", "bailable", "J Balvin", "Energia", "exito"],
    "Adicto": ["reggaeton", "2019", "puerto rico", "pasional", "bailable", "Ozuna", "Tainy", "colaboracion"],
    "Callaíta": ["reggaeton", "2019", "puerto rico", "relajado", "veraniego", "Bad Bunny", "Tainy", "viral"],
    "Tusa": ["reggaeton", "2019", "colombia", "melancolico", "desahogo", "Karol G", "Nicki Minaj", "empoderamiento"],
    "Hawái": ["reggaeton", "2020", "puerto rico", "romantico", "reflexion", "Maluma", "The Weeknd", "version remix"],
    "Bichota": ["reggaeton", "2020", "puerto rico", "empoderado", "fiesta", "Karol G", "KG0516", "himno"],
    "Bésame Mucho": ["bolero", "1940", "mexico", "romantico", "intimo", "Consuelo Velázquez", "Clásicos", "eterno"],
    "Solamente Una Vez": ["bolero", "1941", "mexico", "nostalgico", "romantico", "Agustín Lara", "Inmortales", "clasico"],
    "El Día Que Me Quieras": ["bolero", "1935", "argentina", "poetico", "romantico", "Carlos Gardel", "Gardel", "iconico"],
    "Historia de un Amor": ["bolero", "1955", "panama", "dramatico", "melancolico", "Carlos E. Almarán", "Inolvidables", "universal"],
    "La Gloria Eres Tú": ["bolero", "1950", "cuba", "devocional", "romantico", "José Antonio Méndez", "Boleros", "clasico"],
    "Nosotros": ["bolero", "1953", "cuba", "romantico", "bailable", "Pedro Junco", "Leyendas", "eterno"],
    "Piel Canela": ["bolero", "1953", "puerto rico", "dulce", "romantico", "Bobby Capó", "Boleros", "exito"],
    "Contigo en la Distancia": ["bolero", "1946", "cuba", "melancolico", "reflexion", "César Portillo de la Luz", "Clásicos", "poetico"],
    "Perfidia": ["bolero", "1939", "mexico", "desamor", "nostalgico", "Alberto Domínguez", "Inmortales", "universal"],
    "Sabor a Mí": ["bolero", "1959", "mexico", "intimo", "romantico", "Alvaro Carrillo", "Eternamente", "clasico"],
    "Take Five": ["jazz", "1959", "eeuu", "relajado", "reflexion", "Dave Brubeck", "Time Out", "innovador"],
    "So What": ["jazz", "1959", "eeuu", "modal", "concierto", "Miles Davis", "Kind of Blue", "iconico"],
    "Summertime": ["jazz", "1935", "eeuu", "melancolico", "relajacion", "Ella Fitzgerald", "Porgy and Bess", "standard"],
    "The Girl from Ipanema": ["bossa nova", "1964", "brasil", "seductor", "relajacion", "Antônio Carlos Jobim", "Getz/Gilberto", "exito"],
    "What a Wonderful World": ["jazz", "1967", "eeuu", "optimista", "reflexion", "Louis Armstrong", "What a Wonderful World", "himno"],
    "My Favorite Things": ["jazz", "1961", "eeuu", "alegre", "confort", "John Coltrane", "My Favorite Things", "experimental"],
    "Fly Me to the Moon": ["jazz", "1954", "eeuu", "romantico", "bailable", "Frank Sinatra", "In the Wee Small Hours", "clasico"],
    "Mack the Knife": ["jazz", "1928", "alemania", "narrativo", "bailable", "Bobby Darin", "That's All", "version"],
    "Blue Monk": ["jazz", "1954", "eeuu", "melancolico", "concierto", "Thelonious Monk", "Thelonious Monk", "iconico"],
    "Strange Fruit": ["blues", "1939", "eeuu", "protesta", "reflexion", "Billie Holiday", "Strange Fruit", "historico"],
    "Around the World": ["electronica", "1997", "francia", "repetitivo", "baile", "Daft Punk", "Homework", "innovador"],
    "Sandstorm": ["electronica", "1999", "finlandia", "energico", "fiesta", "Darude", "Before the Storm", "himno"],
    "Levels": ["electronica", "2011", "suecia", "euforico", "fiesta", "Avicii", "Levels", "iconico"],
    "One More Time": ["electronica", "2000", "francia", "festivo", "baile", "Daft Punk", "Discovery", "futurista"],
    "Titanium": ["electronica", "2011", "eeuu", "empoderado", "motivacion", "David Guetta", "Sia", "exito"],
    "Strobe": ["electronica", "2009", "canada", "atmosferico", "relajacion", "Deadmau5", "For Lack of a Better Name", "progresivo"],
    "Language": ["electronica", "2012", "eeuu", "emocional", "baile", "Porter Robinson", "Language", "himno"],
    "Insomnia": ["electronica", "1995", "reino unido", "obsesivo", "fiesta", "Faithless", "Reverence", "clasico"],
    "Children": ["electronica", "1996", "italia", "melodico", "baile", "Robert Miles", "Dreamland", "iconico"],
    "Better Off Alone": ["electronica", "1999", "países bajos", "nostalgico", "baile", "Alice Deejay", "Who Needs Guitars Anyway?", "eurodance"],
    "Lose Yourself": ["rap", "2002", "eeuu", "intenso", "motivacion", "Eminem", "8 Mile", "premio oscar"],
    "Gangsta's Paradise": ["rap", "1995", "eeuu", "oscuro", "reflexion", "Coolio", "Dangerous Minds", "himno"],
    "Juicy": ["rap", "1994", "eeuu", "inspirador", "exito", "The Notorious B.I.G.", "Ready to Die", "clasico"],
    "N.Y. State of Mind": ["rap", "1994", "eeuu", "agresivo", "reflexion", "Nas", "Illmatic", "obra maestra"],
    "In Da Club": ["rap", "2003", "eeuu", "festivo", "fiesta", "50 Cent", "Get Rich or Die Tryin'", "exito"],
    "Hotline Bling": ["rap", "2015", "canada", "melancolico", "baile", "Drake", "Views", "viral"],
    "God's Plan": ["rap", "2018", "canada", "generoso", "motivacion", "Drake", "Scorpion", "filantropico"],
    "Sicko Mode": ["rap", "2018", "eeuu", "caotico", "fiesta", "Travis Scott", "Astroworld", "experimental"],
    "Old Town Road": ["rap", "2019", "eeuu", "innovador", "baile", "Lil Nas X", "7", "fusion country"],
    "HUMBLE": ["rap", "2017", "eeuu", "confiado", "motivacion", "Kendrick Lamar", "DAMN.", "premio pulitzer"],
    "Take Me Home, Country Roads": ["country", "1971", "eeuu", "nostalgico", "viaje", "John Denver", "Poems, Prayers & Promises", "himno"],
    "Jolene": ["country", "1973", "eeuu", "suplicante", "desahogo", "Dolly Parton", "Jolene", "iconico"],
    "The Dance": ["country", "1990", "eeuu", "melancolico", "reflexion", "Garth Brooks", "Garth Brooks", "filosofico"],
    "Wagon Wheel": ["country", "2013", "eeuu", "alegre", "fiesta", "Darius Rucker", "True Believers", "version"],
    "Before He Cheats": ["country", "2005", "eeuu", "vengativo", "desahogo", "Carrie Underwood", "Some Hearts", "empoderamiento"],
    "Friends in Low Places": ["country", "1990", "eeuu", "festivo", "fiesta", "Garth Brooks", "No Fences", "himno"],
    "Man! I Feel Like a Woman!": ["country", "1999", "canada", "empoderado", "fiesta", "Shania Twain", "Come On Over", "iconico"],
    "Ring of Fire": ["country", "1963", "eeuu", "apasionado", "bailable", "Johnny Cash", "Ring of Fire", "clasico"],
    "Tennessee Whiskey": ["country", "2015", "eeuu", "sensual", "romantico", "Chris Stapleton", "Traveller", "version"],
    "Blue Eyes Crying in the Rain": ["country", "1975", "eeuu", "triste", "melancolico", "Willie Nelson", "Red Headed Stranger", "clasico"],
    "Symphony No. 5": ["clasica", "1808", "alemania", "dramatico", "reflexion", "Ludwig van Beethoven", "Sinfonías", "iconico"],
    "The Four Seasons": ["clasica", "1723", "italia", "descriptivo", "relajacion", "Antonio Vivaldi", "Conciertos", "programatico"],
    "Clair de Lune": ["clasica", "1905", "francia", "onirico", "relajacion", "Claude Debussy", "Suite Bergamasque", "impresionista"],
    "Canon in D": ["clasica", "1680", "alemania", "armonioso", "ceremonia", "Johann Pachelbel", "Canon", "popular"],
    "Moonlight Sonata": ["clasica", "1801", "alemania", "melancolico", "reflexion", "Ludwig van Beethoven", "Sonatas", "clasico"],
    "The Blue Danube": ["clasica", "1866", "austria", "elegante", "baile", "Johann Strauss II", "Valses", "iconico"],
    "Boléro": ["clasica", "1928", "francia", "repetitivo", "dramatico", "Maurice Ravel", "Boléro", "experimental"],
    "Eine kleine Nachtmusik": ["clasica", "1787", "austria", "alegre", "entretenimiento", "Wolfgang Amadeus Mozart", "Serenatas", "clasico"],
    "Toccata and Fugue in D minor": ["clasica", "1704", "alemania", "oscuro", "ceremonia", "Johann Sebastian Bach", "Órgano", "dramatico"],
    "1812 Overture": ["clasica", "1880", "rusia", "epico", "concierto", "Pyotr Ilyich Tchaikovsky", "Oberturas", "patriotico"],
    "Mas Que Nada": ["samba", "1963", "brasil", "festivo", "bailable", "Sérgio Mendes", "Brasil '66", "exito"],
    "The Girl from Ipanema": ["bossa nova", "1964", "brasil", "seductor", "relajacion", "Antônio Carlos Jobim", "Getz/Gilberto", "standard"],
    "Garota de Ipanema": ["bossa nova", "1962", "brasil", "poetico", "romantico", "Tom Jobim", "Vinícius de Moraes", "clasico"],
    "Aquarela do Brasil": ["samba", "1939", "brasil", "patriotico", "nostalgico", "Ary Barroso", "Brasil", "himno"],
    "Cucurrucucú Paloma": ["folk", "1954", "mexico", "triste", "melancolico", "Lola Beltrán", "Cucurrucucú", "eterno"],
    "Gracias a la Vida": ["folk", "1966", "chile", "agradecido", "reflexion", "Violeta Parra", "Las Últimas Composiciones", "himno"],
    "Oye Como Va": ["salsa", "1962", "eeuu", "ritmico", "bailable", "Tito Puente", "El Rey Bravo", "version"],
    "La Llorona": ["folk", "1910", "mexico", "dramatico", "nostalgico", "Chavela Vargas", "La Llorona", "leyenda"],
    "Cielito Lindo": ["folk", "1882", "mexico", "alegre", "fiesta", "Quirino Mendoza y Cortés", "Cielito Lindo", "patriotico"],
    "El Choclo": ["tango", "1903", "argentina", "pasional", "bailable", "Ángel Villoldo", "Tango", "clasico"],
    "Waka Waka": ["pop", "2010", "colombia", "festivo", "deportivo", "Shakira", "Fresh", "mundial 2010"],
    "Jerusalema": ["house", "2019", "sudafrica", "alegre", "baile", "Master KG", "Jerusalema", "viral"],
    "Despacito": ["pop latino", "2017", "puerto rico", "sensual", "bailable", "Luis Fonsi", "Daddy Yankee", "record"],
    "Gangnam Style": ["k-pop", "2012", "corea del sur", "humoristico", "baile", "PSY", "PSY 6甲", "fenomeno viral"],
    "Baila Morena": ["lambada", "1989", "brasil", "festivo", "bailable", "Luiz Caldas", "Lambada", "exito"],
    "Zombie": ["rock", "1994", "irlanda", "protesta", "reflexion", "The Cranberries", "No Need to Argue", "politico"],
    "Moscow": ["pop", "2000", "rusia", "nostalgico", "fiesta", "T.A.T.u.", "200 km/h in the Wrong Lane", "controversial"],
    "Nkosi Sikelel' iAfrika": ["himno", "1897", "sudafrica", "solemne", "ceremonia", "Enoch Sontonga", "Himno Nacional", "patriotico"],
    "Malaika": ["folk", "1960", "tanzania", "romantico", "melancolico", "Miriam Makeba", "Miriam Makeba", "clasico"],
    "Smooth Operator": ["r&b", "1984", "reino unido", "seductor", "bailable", "Sade", "Diamond Life", "elegante"],
    "Like a Prayer": ["pop", "1989", "eeuu", "espiritual", "baile", "Madonna", "Like a Prayer", "controversial"],
    "Billie Jean": ["pop", "1982", "eeuu", "misterioso", "baile", "Michael Jackson", "Thriller", "iconico"],
    "Sweet Dreams": ["synthpop", "1983", "reino unido", "onirico", "baile", "Eurythmics", "Sweet Dreams", "clasico"],
    "Take On Me": ["synthpop", "1985", "noruega", "romantico", "baile", "a-ha", "Hunting High and Low", "animacion"],
    "Every Breath You Take": ["rock", "1983", "reino unido", "obsesivo", "reflexion", "The Police", "Synchronicity", "exito"],
    "Tainted Love": ["new wave", "1981", "reino unido", "dramatico", "baile", "Soft Cell", "Non-Stop Erotic Cabaret", "version"],
    "Girls Just Want to Have Fun": ["new wave", "1983", "eeuu", "alegre", "fiesta", "Cyndi Lauper", "She's So Unusual", "himno"],
    "Africa": ["rock", "1982", "eeuu", "exotico", "nostalgico", "Toto", "Toto IV", "culto"],
    "Karma Chameleon": ["pop", "1983", "reino unido", "colorido", "bailable", "Culture Club", "Colour by Numbers", "exito"],
    "I Wanna Dance with Somebody": ["pop", "1987", "eeuu", "euforico", "fiesta", "Whitney Houston", "Whitney", "clasico"],
    "Smells Like Teen Spirit": ["grunge", "1991", "eeuu", "rebelde", "fiesta", "Nirvana", "Nevermind", "himno"],
    "Wonderwall": ["rock", "1995", "reino unido", "melancolico", "acustico", "Oasis", "(What's the Story) Morning Glory?", "iconico"],
    "I Will Always Love You": ["pop", "1992", "eeuu", "dramatico", "romantico", "Whitney Houston", "The Bodyguard", "exito"],
    "No Scrubs": ["r&b", "1999", "eeuu", "empoderado", "baile", "TLC", "FanMail", "himno"],
    "Waterfalls": ["r&b", "1995", "eeuu", "reflexivo", "consciente", "TLC", "CrazySexyCool", "social"],
    "Creep": ["rock", "1992", "reino unido", "alienado", "desahogo", "Radiohead", "Pablo Honey", "himno"],
    "Losing My Religion": ["rock alternativo", "1991", "eeuu", "ansioso", "reflexion", "R.E.M.", "Out of Time", "exito"],
    "Wannabe": ["pop", "1996", "reino unido", "alegre", "fiesta", "Spice Girls", "Spice", "iconico"],
    "Baby One More Time": ["pop", "1998", "eeuu", "adolescente", "baile", "Britney Spears", "...Baby One More Time", "fenomeno"],
    "California Love": ["rap", "1995", "eeuu", "festivo", "fiesta", "2Pac", "All Eyez on Me", "himno"],
    "Hey Ya!": ["pop", "2003", "eeuu", "energico", "fiesta", "OutKast", "Speakerboxxx/The Love Below", "contagioso"],
    "Umbrella": ["pop", "2007", "eeuu", "dramatico", "baile", "Rihanna", "Good Girl Gone Bad", "iconico"],
    "Poker Face": ["pop", "2008", "eeuu", "misterioso", "baile", "Lady Gaga", "The Fame", "exito"],
    "Viva la Vida": ["rock", "2008", "reino unido", "epico", "reflexion", "Coldplay", "Viva la Vida or Death and All His Friends", "orquestal"],
    "Hips Don't Lie": ["pop", "2006", "colombia", "sensual", "bailable", "Shakira", "Oral Fixation Vol. 2", "exito"],
    "Crazy in Love": ["r&b", "2003", "eeuu", "apasionado", "baile", "Beyoncé", "Dangerously in Love", "iconico"],
    "Yeah!": ["crunk", "2004", "eeuu", "festivo", "fiesta", "Usher", "Confessions", "exito"],
    "Since U Been Gone": ["pop rock", "2004", "eeuu", "catartico", "desahogo", "Kelly Clarkson", "Breakaway", "himno"],
    "Low": ["crunk", "2007", "eeuu", "sensual", "baile", "Flo Rida", "Mail on Sunday", "viral"],
    "Bleeding Love": ["pop", "2007", "reino unido", "emocional", "romantico", "Leona Lewis", "Spirit", "exito"],
    "Uptown Funk": ["pop", "2014", "eeuu", "festivo", "fiesta", "Mark Ronson", "Bruno Mars", "retro"],
    "Shape of You": ["pop", "2017", "reino unido", "sensual", "bailable", "Ed Sheeran", "÷", "record"],
    "Old Town Road": ["rap", "2019", "eeuu", "innovador", "baile", "Lil Nas X", "7", "fusion"],
    "Bad Guy": ["pop", "2019", "eeuu", "ironico", "baile", "Billie Eilish", "When We All Fall Asleep", "premio grammy"],
    "Despacito": ["pop latino", "2017", "puerto rico", "sensual", "bailable", "Luis Fonsi", "Daddy Yankee", "viral"],
    "Blinding Lights": ["pop", "2019", "canada", "nostalgico", "conduccion", "The Weeknd", "After Hours", "synthwave"],
    "Rolling in the Deep": ["pop", "2010", "reino unido", "pasional", "desahogo", "Adele", "21", "exito"],
    "Happy": ["pop", "2013", "eeuu", "alegre", "baile", "Pharrell Williams", "Girl", "himno"],
    "See You Again": ["rap", "2015", "eeuu", "emocional", "homenaje", "Wiz Khalifa", "Furious 7", "tributo"],
    "Shallow": ["pop", "2018", "eeuu", "intenso", "dueto", "Lady Gaga", "A Star Is Born", "premio oscar"],
    "De Música Ligera": ["rock latino", "1990", "argentina", "nostalgico", "concierto", "Soda Stereo", "Canción Animal", "iconico"],
    "Persiana Americana": ["rock latino", "1986", "argentina", "misterioso", "reflexion", "Soda Stereo", "Signos", "clasico"],
    "Lobo Hombre en París": ["rock", "1984", "espana", "onirico", "mitologico", "La Unión", "Mil Siluetas", "version"],
    "La Muralla Verde": ["rock", "1994", "peru", "melancolico", "nostalgia", "Los Mojarras", "Los Mojarras", "culto"],
    "Matador": ["rock", "1993", "argentina", "intenso", "concierto", "Los Fabulosos Cadillacs", "El León", "exito"],
    "Mal Bicho": ["rock", "1994", "argentina", "protesta", "reivindicacion", "Los Fabulosos Cadillacs", "Vasos Vacíos", "social"],
    "Bolero Falaz": ["rock", "1990", "argentina", "dramatico", "romantico", "Aterciopelados", "Con el Corazón en la Mano", "clasico"],
    "Flaca": ["rock", "1997", "argentina", "ironico", "desamor", "Andrés Calamaro", "Alta Suciedad", "himno"],
    "Lamento Boliviano": ["rock", "1994", "argentina", "apasionado", "desahogo", "Enanitos Verdes", "Big Bang", "iconico"],
    "Cuando Pase el Temblor": ["rock", "1985", "argentina", "atmosferico", "concierto", "Soda Stereo", "Nada Personal", "eterno"],
    "La Ventanita": ["cumbia", "1994", "argentina", "romantico", "bailable", "Los Manseros Santiagueños", "La Ventanita", "clasico"],
    "Nunca Pense Llorar": ["cumbia", "2014", "argentina", "melancolico", "desahogo", "Leo Mattioli", "Hasta el Final", "emocional"],
    "Soy Soltero": ["cumbia", "2007", "argentina", "divertido", "fiesta", "El Dipy", "El Dipy", "popular"],
    "La Pollera Colorá": ["cumbia", "1962", "colombia", "festivo", "bailable", "Carmen Miranda", "Grandes Exitos", "iconico"],
    "Cariñito": ["cumbia", "1978", "peru", "dulce", "romantico", "Los Hijos del Sol", "Cariñito", "clasico"],
    "Guaracha Sabroso": ["guaracha", "1970", "cuba", "alegre", "bailable", "La Sonora Matancera", "Sabroso", "tropical"],
    "La Colegiala": ["cumbia", "1975", "colombia", "nostalgico", "bailable", "Rodolfo y su Tipica", "La Colegiala", "universal"],
    "El Baile del Gorila": ["cumbia", "2000", "mexico", "divertido", "fiesta", "Tropicalísimo Apache", "El Baile del Gorila", "viral"],
    "Mi Cucu": ["cumbia", "2002", "argentina", "picaro", "bailable", "La Sonora de Tommy Rey", "Mi Cucu", "contagioso"],
    "La Cumbia de la Cerveza": ["cumbia", "2015", "argentina", "festivo", "fiesta", "Tru La La", "La Cumbia de la Cerveza", "himno"],
    "Llorando Se Fue": ["saya", "1981", "bolivia", "melancolico", "bailable", "Los Kjarkas", "Canto a la Mujer de Mi Pueblo", "lambada"],
    "El Condor Pasa": ["folk", "1913", "peru", "epico", "reflexion", "Daniel Alomía Robles", "El Cóndor Pasa", "patrimonio"],
    "Ojos Azules": ["huayno", "1980", "peru", "romantico", "nostalgia", "Los Andes de Puno", "Ojos Azules", "tradicional"],
    "Viento": ["folk", "1975", "argentina", "poetico", "reflexion", "Los Chalchaleros", "Viento", "clasico"],
    "Zamba de Mi Esperanza": ["zamba", "1940", "argentina", "nostalgico", "romantico", "Luis Alberto Martínez", "Zambas", "eterno"],
    "La Felipe Varela": ["chacarera", "1965", "argentina", "epico", "bailable", "Los Hermanos Ábalos", "Chacareras", "historico"],
    "Alfonsina y el Mar": ["folk", "1969", "argentina", "triste", "homenaje", "Mercedes Sosa", "El Grito de la Tierra", "poetico"],
    "Duerme Negrito": ["folk", "1969", "argentina", "dulce", "arrullo", "Mercedes Sosa", "Mujeres Argentinas", "tradicional"],
    "Canción con Todos": ["folk", "1970", "argentina", "unificador", "himno", "Mercedes Sosa", "Canción con Todos", "latinoamericano"],
    "Luna Tucumana": ["zamba", "1940", "argentina", "nostalgico", "romantico", "Mercedes Sosa", "Luna Tucumana", "clasico"],
    "Por una Cabeza": ["tango", "1935", "argentina", "dramatico", "baile", "Carlos Gardel", "Por una Cabeza", "cinematografico"],
    "El Día Que Me Quieras": ["tango", "1935", "argentina", "romantico", "nostalgia", "Carlos Gardel", "El Día Que Me Quieras", "eterno"],
    "Caminito": ["tango", "1926", "argentina", "nostalgico", "melancolico", "Carlos Gardel", "Caminito", "clasico"],
    "La Cumparsita": ["tango", "1917", "uruguay", "dramatico", "baile", "Gerardo Matos Rodríguez", "La Cumparsita", "himno"],
    "Balada para un Loco": ["tango", "1969", "argentina", "bohemio", "teatral", "Astor Piazzolla", "Balada para un Loco", "vanguardista"],
    "Adiós Nonino": ["tango", "1959", "argentina", "emocional", "homenaje", "Astor Piazzolla", "Adiós Nonino", "masterpiece"],
    "Naranjo en Flor": ["tango", "1944", "argentina", "poetico", "melancolico", "Enrique Santos Discépolo", "Naranjo en Flor", "clasico"],
    "Malena": ["tango", "1942", "argentina", "nostalgico", "romantico", "Lucio Demare", "Malena", "cantable"],
    "Volver": ["tango", "1935", "argentina", "reflexivo", "nostalgia", "Carlos Gardel", "Volver", "universal"],
    "Uno": ["tango", "1943", "argentina", "dramatico", "desamor", "Enrique Santos Discépolo", "Uno", "clasico"],
    "Chega de Saudade": ["bossa nova", "1958", "brasil", "nostalgico", "romantico", "João Gilberto", "Chega de Saudade", "fundacional"],
    "Águas de Março": ["bossa nova", "1972", "brasil", "poetico", "reflexion", "Tom Jobim", "Jobim", "obra maestra"],
    "Mas Que Nada": ["samba", "1963", "brasil", "festivo", "bailable", "Jorge Ben Jor", "Samba Esquema Novo", "iconico"],
    "Aquele Abraço": ["samba", "1969", "brasil", "alegre", "homenaje", "Gilberto Gil", "Aquele Abraço", "cultural"],
    "Construção": ["mpb", "1971", "brasil", "poetico", "reflexion", "Chico Buarque", "Construção", "social"],
    "Trem das Onze": ["samba", "1964", "brasil", "nostalgico", "romantico", "Adoniran Barbosa", "Adoniran Barbosa", "clasico"],
    "Oceano": ["mpb", "1989", "brasil", "sensual", "romantico", "Djavan", "Lilás", "exito"],
    "Sozinho": ["pop", "1998", "brasil", "melancolico", "desahogo", "Caetano Veloso", "Livro", "himno"],
    "Proibida pra Mim": ["samba", "2018", "brasil", "alegre", "bailable", "Charlie Brown Jr.", "Camisa 10 Joga Bola Até na Chuva", "rock-samba"],
    "Dança da Solidão": ["samba", "1972", "brasil", "melancolico", "reflexion", "Paulinho da Viola", "Dança da Solidão", "poetico"],
    "Kind of Blue": ["jazz", "1959", "eeuu", "modal", "relajacion", "Miles Davis", "Kind of Blue", "revolucionario"],
    "A Love Supreme": ["jazz", "1965", "eeuu", "espiritual", "meditacion", "John Coltrane", "A Love Supreme", "trascendental"],
    "Take the A Train": ["jazz", "1939", "eeuu", "alegre", "bailable", "Duke Ellington", "Take the A Train", "standard"],
    "Body and Soul": ["jazz", "1930", "eeuu", "romantico", "intimo", "Coleman Hawkins", "Body and Soul", "clasico"],
    "Stormy Monday": ["blues", "1947", "eeuu", "melancolico", "desahogo", "T-Bone Walker", "Stormy Monday", "electrificado"],
    "The Thrill Is Gone": ["blues", "1969", "eeuu", "desolado", "desamor", "B.B. King", "Completely Well", "iconico"],
    "Crossroad Blues": ["blues", "1936", "eeuu", "urgente", "mitologico", "Robert Johnson", "King of the Delta Blues", "leyenda"],
    "Misty": ["jazz", "1954", "eeuu", "romantico", "intimo", "Erroll Garner", "Misty", "standard"],
    "Autumn Leaves": ["jazz", "1945", "francia", "nostalgico", "reflexion", "Joseph Kosma", "Autumn Leaves", "versionado"],
    "All Blues": ["jazz", "1959", "eeuu", "modal", "relajacion", "Miles Davis", "Kind of Blue", "innovador"],
    "The Rite of Spring": ["clasica", "1913", "rusia", "primitivo", "concierto", "Igor Stravinsky", "The Rite of Spring", "escandalo"],
    "Clair de Lune": ["clasica", "1905", "francia", "onirico", "relajacion", "Claude Debussy", "Suite Bergamasque", "impresionista"],
    "Gymnopédie No. 1": ["clasica", "1888", "francia", "melancolico", "meditacion", "Erik Satie", "Gymnopédies", "minimalista"],
    "Rhapsody in Blue": ["clasica", "1924", "eeuu", "energico", "concierto", "George Gershwin", "Rhapsody in Blue", "jazz-classical"],
    "Adagio for Strings": ["clasica", "1936", "eeuu", "dramatico", "funebre", "Samuel Barber", "Adagio for Strings", "emocional"],
    "Carmina Burana": ["clasica", "1936", "alemania", "dramatico", "coro", "Carl Orff", "Carmina Burana", "epico"],
    "The Planets": ["clasica", "1916", "reino unido", "cosmico", "orquestal", "Gustav Holst", "The Planets", "programatico"],
    "Symphony No. 9": ["clasica", "1909", "austria", "angustiado", "reflexion", "Gustav Mahler", "Symphony No. 9", "existencial"],
    "Prelude in C-sharp minor": ["clasica", "1892", "rusia", "dramatico", "virtuosismo", "Sergei Rachmaninoff", "Morceaux de fantaisie", "iconico"],
    "The Firebird": ["clasica", "1910", "rusia", "magico", "ballet", "Igor Stravinsky", "The Firebird", "fantastico"],
    "Windowlicker": ["electronica", "1999", "reino unido", "psicodelico", "baile", "Aphex Twin", "Windowlicker", "vanguardista"],
    "Breathe": ["electronica", "1995", "reino unido", "atmosferico", "relajacion", "The Prodigy", "The Fat of the Land", "rave"],
    "Porcelain": ["electronica", "1999", "eeuu", "delicado", "meditacion", "Moby", "Play", "sample"],
    "Around the World": ["electronica", "1997", "francia", "repetitivo", "baile", "Daft Punk", "Homework", "minimalista"],
    "Insomnia": ["electronica", "1995", "reino unido", "obsesivo", "fiesta", "Faithless", "Reverence", "trance"],
    "Sandstorm": ["electronica", "1999", "finlandia", "energico", "deportivo", "Darude", "Before the Storm", "himno"],
    "Strobe": ["electronica", "2009", "canada", "progresivo", "viaje", "Deadmau5", "For Lack of a Better Name", "epico"],
    "Language": ["electronica", "2012", "eeuu", "emocional", "baile", "Porter Robinson", "Language", "progresivo"],
    "Opus": ["electronica", "2015", "alemania", "trascendental", "fiesta", "Eric Prydz", "Opus", "progresivo"],
    "Latch": ["electronica", "2012", "reino unido", "sensual", "baile", "Disclosure", "Settle", "garage"],
    "The Message": ["hip-hop", "1982", "eeuu", "social", "reflexion", "Grandmaster Flash", "The Message", "consciente"],
    "Fight the Power": ["hip-hop", "1989", "eeuu", "protesta", "reivindicacion", "Public Enemy", "Fear of a Black Planet", "politico"],
    "N.Y. State of Mind": ["hip-hop", "1994", "eeuu", "crudo", "reflexion", "Nas", "Illmatic", "obra maestra"],
    "Changes": ["hip-hop", "1998", "eeuu", "social", "reflexion", "2Pac", "Greatest Hits", "eterno"],
    "Juicy": ["hip-hop", "1994", "eeuu", "inspirador", "superacion", "The Notorious B.I.G.", "Ready to Die", "clasico"],
    "93 'Til Infinity": ["hip-hop", "1993", "eeuu", "filosofico", "reflexion", "Souls of Mischief", "93 'Til Infinity", "underground"],
    "I Used to Love H.E.R.": ["hip-hop", "1994", "eeuu", "alegorico", "reflexion", "Common", "Resurrection", "metaforico"],
    "They Reminisce Over You": ["hip-hop", "1992", "eeuu", "nostalgico", "homenaje", "Pete Rock & CL Smooth", "Mecca and the Soul Brother", "jazz rap"],
    "Shook Ones Pt. II": ["hip-hop", "1995", "eeuu", "paranoico", "batalla", "Mobb Deep", "The Infamous", "oscuro"],
    "The World Is Yours": ["hip-hop", "1994", "eeuu", "ambicioso", "motivacion", "Nas", "Illmatic", "inspirador"],
    "Jolene": ["country", "1973", "eeuu", "suplicante", "desahogo", "Dolly Parton", "Jolene", "iconico"],
    "The Devil Went Down to Georgia": ["country", "1979", "eeuu", "narrativo", "competencia", "The Charlie Daniels Band", "Million Mile Reflections", "virtuosismo"],
    "Always on My Mind": ["country", "1972", "eeuu", "arrepentido", "romantico", "Willie Nelson", "Always on My Mind", "version"],
    "Ring of Fire": ["country", "1963", "eeuu", "apasionado", "bailable", "Johnny Cash", "Ring of Fire", "clasico"],
    "Coal Miner's Daughter": ["country", "1970", "eeuu", "autobiografico", "nostalgia", "Loretta Lynn", "Coal Miner's Daughter", "historico"],
    "Friends in Low Places": ["country", "1990", "eeuu", "festivo", "fiesta", "Garth Brooks", "No Fences", "himno"],
    "Man! I Feel Like a Woman!": ["country", "1999", "canada", "empoderado", "fiesta", "Shania Twain", "Come On Over", "crossover"],
    "Before He Cheats": ["country", "2005", "eeuu", "vengativo", "desahogo", "Carrie Underwood", "Some Hearts", "femenino"],
    "Wagon Wheel": ["country", "2013", "eeuu", "alegre", "viaje", "Darius Rucker", "True Believers", "folk"],
    "Tennessee Whiskey": ["country", "2015", "eeuu", "sensual", "romantico", "Chris Stapleton", "Traveller", "soul"],
    "Malaika": ["folk", "1960", "tanzania", "romantico", "melancolico", "Miriam Makeba", "Miriam Makeba", "swahili"],
    "Pata Pata": ["afropop", "1967", "sudafrica", "festivo", "bailable", "Miriam Makeba", "Pata Pata", "exito"],
    "Yèkèrmo Sèw": ["ethio-jazz", "1974", "etiopia", "hipnotico", "baile", "Mulatu Astatke", "Mulatu of Ethiopia", "vanguardista"],
    "Soukora": ["world", "2000", "mali", "melancolico", "reflexion", "Ali Farka Touré", "The River", "blues"],
    "Dembe": ["world", "1994", "senegal", "alegre", "bailable", "Youssou N'Dour", "The Guide (Wommat)", "fusion"],
    "The Lion Sleeps Tonight": ["folk", "1939", "sudafrica", "nostalgico", "folk", "Solomon Linda", "The Lion Sleeps Tonight", "versionado"],
    "Jai Ho": ["bhangra", "2008", "india", "euforico", "baile", "A.R. Rahman", "Slumdog Millionaire", "premio oscar"],
    "Koi Mil Gaya": ["bollywood", "2003", "india", "romantico", "cinematografico", "Udit Narayan", "Kuch Kuch Hota Hai", "exito"],
    "Gangnam Style": ["k-pop", "2012", "corea del sur", "humoristico", "baile", "PSY", "PSY 6甲", "viral"],
    "Sukiyaki": ["pop", "1961", "japon", "melancolico", "romantico", "Kyu Sakamoto", "Sukiyaki", "internacional"],
    "Stairway to Heaven": ["rock", "1971", "reino unido", "epico", "concierto", "Led Zeppelin", "Led Zeppelin IV", "leyenda"],
    "Bohemian Rhapsody": ["rock", "1975", "reino unido", "operistico", "experimental", "Queen", "A Night at the Opera", "innovador"],
    "Hotel California": ["rock", "1976", "eeuu", "misterioso", "reflexion", "Eagles", "Hotel California", "clasico"],
    "Imagine": ["rock", "1971", "reino unido", "utopico", "paz", "John Lennon", "Imagine", "himno"],
    "Sweet Home Alabama": ["rock", "1974", "eeuu", "sureño", "fiesta", "Lynyrd Skynyrd", "Second Helping", "iconico"],
    "Dream On": ["rock", "1973", "eeuu", "ambicioso", "motivacion", "Aerosmith", "Aerosmith", "power ballad"],
    "Brown Sugar": ["rock", "1971", "reino unido", "sensual", "bailable", "The Rolling Stones", "Sticky Fingers", "controversial"],
    "More Than a Feeling": ["rock", "1976", "eeuu", "nostalgico", "melancolico", "Boston", "Boston", "arena rock"],
    "Highway to Hell": ["rock", "1979", "australia", "rebelde", "fiesta", "AC/DC", "Highway to Hell", "himno"],
    "Comfortably Numb": ["rock", "1979", "reino unido", "psicodelico", "reflexion", "Pink Floyd", "The Wall", "epico"],
    "Sweet Dreams": ["synthpop", "1983", "reino unido", "onirico", "baile", "Eurythmics", "Sweet Dreams", "iconico"],
    "Take On Me": ["synthpop", "1985", "noruega", "romantico", "baile", "a-ha", "Hunting High and Low", "animacion"],
    "Tainted Love": ["new wave", "1981", "reino unido", "dramatico", "baile", "Soft Cell", "Non-Stop Erotic Cabaret", "version"],
    "Girls Just Want to Have Fun": ["new wave", "1983", "eeuu", "femenino", "fiesta", "Cyndi Lauper", "She's So Unusual", "empoderamiento"],
    "Every Breath You Take": ["rock", "1983", "reino unido", "obsesivo", "romantico", "The Police", "Synchronicity", "exito"],
    "Billie Jean": ["pop", "1982", "eeuu", "misterioso", "baile", "Michael Jackson", "Thriller", "breakthrough"],
    "Like a Virgin": ["pop", "1984", "eeuu", "provocativo", "baile", "Madonna", "Like a Virgin", "polémico"],
    "With or Without You": ["rock", "1987", "irlanda", "intenso", "romantico", "U2", "The Joshua Tree", "emocional"],
    "Don't You Want Me": ["synthpop", "1981", "reino unido", "dramatico", "baile", "The Human League", "Dare!", "narrativo"],
    "Blue Monday": ["new wave", "1983", "reino unido", "melancolico", "baile", "New Order", "Power, Corruption & Lies", "innovador"],
    "Smells Like Teen Spirit": ["grunge", "1991", "eeuu", "rebelde", "fiesta", "Nirvana", "Nevermind", "generacional"],
    "Wonderwall": ["britpop", "1995", "reino unido", "melancolico", "acustico", "Oasis", "(What's the Story) Morning Glory?", "himno"],
    "Bitter Sweet Symphony": ["britpop", "1997", "reino unido", "epico", "reflexion", "The Verve", "Urban Hymns", "orquestal"],
    "Creep": ["rock", "1992", "reino unido", "alienado", "desahogo", "Radiohead", "Pablo Honey", "inseguridad"],
    "Losing My Religion": ["rock alternativo", "1991", "eeuu", "ansioso", "reflexion", "R.E.M.", "Out of Time", "exito"],
    "Black Hole Sun": ["grunge", "1994", "eeuu", "surreal", "reflexion", "Soundgarden", "Superunknown", "onirico"],
    "Parklife": ["britpop", "1994", "reino unido", "satirico", "bailable", "Blur", "Parklife", "britanico"],
    "I Will Always Love You": ["pop", "1992", "eeuu", "dramatico", "romantico", "Whitney Houston", "The Bodyguard", "poder vocal"],
    "Waterfalls": ["r&b", "1995", "eeuu", "social", "reflexion", "TLC", "CrazySexyCool", "consciente"],
    "No Scrubs": ["r&b", "1999", "eeuu", "empoderado", "baile", "TLC", "FanMail", "feminista"],
    "Hey Ya!": ["pop", "2003", "eeuu", "energico", "fiesta", "OutKast", "Speakerboxxx/The Love Below", "contagioso"],
    "Crazy in Love": ["r&b", "2003", "eeuu", "apasionado", "baile", "Beyoncé", "Dangerously in Love", "iconico"],
    "Umbrella": ["pop", "2007", "eeuu", "dramatico", "baile", "Rihanna", "Good Girl Gone Bad", "exito"],
    "Viva la Vida": ["rock", "2008", "reino unido", "epico", "reflexion", "Coldplay", "Viva la Vida or Death and All His Friends", "orquestal"],
    "Poker Face": ["pop", "2008", "eeuu", "misterioso", "baile", "Lady Gaga", "The Fame", "electropop"],
    "Hips Don't Lie": ["pop", "2006", "colombia", "sensual", "bailable", "Shakira", "Oral Fixation Vol. 2", "fusion"],
    "Since U Been Gone": ["pop rock", "2004", "eeuu", "catartico", "desahogo", "Kelly Clarkson", "Breakaway", "himno"],
    "Boulevard of Broken Dreams": ["rock alternativo", "2004", "eeuu", "melancolico", "soledad", "Green Day", "American Idiot", "emo"],
    "Rehab": ["soul", "2006", "reino unido", "defiant", "desahogo", "Amy Winehouse", "Back to Black", "retro"],
    "SexyBack": ["pop", "2006", "eeuu", "provocativo", "baile", "Justin Timberlake", "FutureSex/LoveSounds", "futurista"],
    "Uptown Funk": ["pop", "2014", "eeuu", "festivo", "fiesta", "Mark Ronson", "Uptown Special", "retro"],
    "Shape of You": ["pop", "2017", "reino unido", "sensual", "bailable", "Ed Sheeran", "÷", "record"],
    "Old Town Road": ["country rap", "2019", "eeuu", "innovador", "baile", "Lil Nas X", "7", "viral"],
    "Bad Guy": ["pop", "2019", "eeuu", "ironico", "baile", "Billie Eilish", "When We All Fall Asleep", "premio grammy"],
    "Blinding Lights": ["synthwave", "2019", "canada", "nostalgico", "conduccion", "The Weeknd", "After Hours", "80s"],
    "Rolling in the Deep": ["pop", "2010", "reino unido", "pasional", "desahogo", "Adele", "21", "exito"],
    "Happy": ["pop", "2013", "eeuu", "alegre", "baile", "Pharrell Williams", "Girl", "himno"],
    "Formation": ["r&b", "2016", "eeuu", "empoderado", "reivindicacion", "Beyoncé", "Lemonade", "politico"],
    "God's Plan": ["rap", "2018", "canada", "generoso", "motivacion", "Drake", "Scorpion", "filantropico"],
    "Shallow": ["pop", "2018", "eeuu", "intenso", "dueto", "Lady Gaga", "A Star Is Born", "premio oscar"],
    "Sensualidad": ["reggaeton", "2017", "puerto rico", "sensual", "bailable", "Bad Bunny", "J Balvin", "Prince Royce"],
    "Te Boté - Remix": ["reggaeton", "2018", "puerto rico", "melancolico", "desahogo", "Casper Magico", "Nio Garcia", "colaboracion masiva"],
    "China": ["reggaeton", "2019", "puerto rico", "festivo", "fiesta", "Anuel AA", "Daddy Yankee", "fusion urbana"],
    "Adicto": ["reggaeton", "2019", "puerto rico", "pasional", "bailable", "Tainy", "Ozuna", "Anuel AA"],
    "Fiel": ["reggaeton", "2021", "puerto rico", "romantico", "bailable", "Los Legendarios", "Wisin", "Myke Towers"],
    "Pareja del Año": ["reggaeton", "2021", "colombia", "romantico", "bailable", "Sebastian Yatra", "Duki", "fusion pop"],
    "Todo de Ti": ["pop latino", "2021", "puerto rico", "festivo", "fiesta", "Rauw Alejandro", "Vice Versa", "retro 80s"],
    "Yonaguni": ["reggaeton", "2021", "puerto rico", "melancolico", "reflexion", "Bad Bunny", "Yonaguni", "japonés"],
    "Poblado - Remix": ["reggaeton", "2021", "colombia", "nostalgico", "bailable", "J Balvin", "Karol G", "colaboracion"],
    "Volví": ["reggaeton", "2021", "puerto rico", "nostalgico", "bailable", "Aventura", "Bad Bunny", "reunion"],
    "Valió la Pena": ["salsa", "2004", "puerto rico", "romantico", "bailable", "Marc Anthony", "Amar Sin Mentiras", "exito"],
    "La Agarro Bajando": ["salsa", "2005", "colombia", "picaro", "bailable", "Gilberto Santa Rosa", "Directo al Corazón", "divertido"],
    "Vivir Lo Nuestro": ["salsa", "1993", "puerto rico", "romantico", "bailable", "Marc Anthony", "La Mala", "dueto"],
    "Casi Te Envidio": ["salsa", "2008", "puerto rico", "pasional", "bailable", "Andy Montañez", "Salsa Classics", "clasico"],
    "Que Alguien Me Diga": ["salsa", "1998", "puerto rico", "dramatico", "bailable", "Gilberto Santa Rosa", "Expresión", "exito"],
    "La Carretera": ["salsa", "1994", "puerto rico", "nostalgico", "bailable", "Prince Royce", "FIVE", "fusion"],
    "Tengo Ganas": ["salsa", "2003", "cuba", "sensual", "bailable", "Victor Manuelle", "Travesia", "timba"],
    "Deja que la Vida Fluya": ["salsa", "2018", "colombia", "positivo", "bailable", "Mauricio & Palo de Agua", "Canto por Cantar", "moderna"],
    "Amor de Locos": ["salsa", "1986", "puerto rico", "apasionado", "bailable", "Luis Enrique", "Amor de Locos", "clasico"],
    "La Rueda": ["salsa", "2001", "cuba", "festivo", "bailable", "Los Van Van", "Chapeando", "cubana"],
    "Aventura": ["bachata", "2002", "republica dominicana", "romantico", "bailable", "Aventura", "We Broke the Rules", "innovador"],
    "Eres Mía": ["bachata", "2014", "republica dominicana", "posesivo", "romantico", "Romeo Santos", "Formula, Vol. 2", "exito"],
    "Promise": ["bachata", "2019", "republica dominicana", "romantico", "bailable", "Romeo Santos", "Utopia", "ingles"],
    "Madre": ["bachata", "2021", "republica dominicana", "tributo", "reflexion", "Romeo Santos", "Utopia", "emocional"],
    "Dile al Amor": ["bachata", "2010", "republica dominicana", "melancolico", "desahogo", "Aventura", "The Last", "despedida"],
    "Stand by Me": ["bachata", "2019", "republica dominicana", "nostalgico", "bailable", "Prince Royce", "Alter Ego", "version"],
    "Inmortal": ["bachata", "2018", "republica dominicana", "epico", "romantico", "Romeo Santos", "Golden", "orquestal"],
    "Recházame": ["bachata", "2005", "republica dominicana", "suplicante", "romantico", "Prince Royce", "Prince Royce", "clasico"],
    "La Maravilla": ["bachata", "2020", "republica dominicana", "alegre", "bailable", "Raulin Rodriguez", "La Maravilla", "tradicional"],
    "Vagabundo": ["bachata", "1998", "republica dominicana", "melancolico", "desahogo", "Joe Veras", "Carta de Verano", "clasico"],
    "Rayando el Sol": ["pop rock", "2010", "mexico", "melancolico", "romantico", "Maná", "Drama y Luz", "exito"],
    "Clavado en un Bar": ["pop rock", "1995", "mexico", "nostalgico", "desahogo", "Maná", "Cuando los Ángeles Lloran", "clasico"],
    "Labios Compartidos": ["rock latino", "2005", "mexico", "reflexivo", "romantico", "Maná", "Amar es Combatir", "moderno"],
    "En el Muelle de San Blas": ["rock", "1997", "mexico", "tragico", "romantico", "Maná", "Sueños Líquidos", "leyenda"],
    "Oye Mi Amor": ["rock", "1992", "mexico", "alegre", "bailable", "Maná", "¿Dónde Jugarán los Niños?", "iconico"],
    "Te Lo Pido por Favor": ["rock", "1994", "argentina", "suplicante", "romantico", "Ratones Paranoicos", "Todo de Nuevo", "rock urbano"],
    "Loco": ["pop rock", "2001", "argentina", "pasional", "romantico", "Andrés Calamaro", "El Salmón", "exito"],
    "Sin Documentos": ["rock", "1994", "argentina", "rebelde", "romantico", "Los Rodríguez", "Sin Documentos", "clasico"],
    "Flores": ["pop rock", "2023", "argentina", "superacion", "reflexion", "Dante Spinetta", "Mesa Dulce", "moderno"],
    "Crimen": ["rock", "2006", "argentina", "dramatico", "reflexion", "Gustavo Cerati", "Ahí Vamos", "poetico"],
    "Titanium": ["electronica", "2011", "francia", "empoderado", "motivacion", "David Guetta", "Sia", "himno"],
    "Don't You Worry Child": ["electronica", "2012", "suecia", "esperanzador", "fiesta", "Swedish House Mafia", "Until Now", "progresivo"],
    "Wake Me Up": ["electronica", "2013", "suecia", "folk", "viaje", "Avicii", "True", "fusion"],
    "Animals": ["electronica", "2013", "paises bajos", "intenso", "fiesta", "Martin Garrix", "Gold Skies", "big room"],
    "Tsunami": ["electronica", "2013", "paises bajos", "explosivo", "fiesta", "DVBBS", "Tsunami", "drop"],
    "Lean On": ["electronica", "2015", "india", "exotico", "baile", "Major Lazer", "Peace Is the Mission", "viral"],
    "Closer": ["electronica", "2016", "eeuu", "nostalgico", "baile", "The Chainsmokers", "Collage", "indie dance"],
    "Silence": ["electronica", "2017", "noruega", "atmosferico", "meditacion", "Marshmello", "Silence", "tropical"],
    "The Middle": ["electronica", "2018", "eeuu", "optimista", "baile", "Zedd", "The Middle", "comercial"],
    "L'Amour Toujours": ["electronica", "2001", "italia", "romantico", "baile", "Gigi D'Agostino", "L'Amour Toujours", "eurodance"],
    "Hotline Bling": ["rap", "2015", "canada", "melancolico", "baile", "Drake", "Views", "meme"],
    "God's Plan": ["rap", "2018", "canada", "generoso", "motivacion", "Drake", "Scorpion", "filantropico"],
    "Sicko Mode": ["rap", "2018", "eeuu", "experimental", "fiesta", "Travis Scott", "Astroworld", "psicodelico"],
    "Rockstar": ["rap", "2017", "eeuu", "rebelde", "fiesta", "Post Malone", "Beerbongs & Bentleys", "rock rap"],
    "Bad and Boujee": ["rap", "2016", "eeuu", "ostentoso", "fiesta", "Migos", "Culture", "trap"],
    "Bodak Yellow": ["rap", "2017", "eeuu", "empoderado", "desahogo", "Cardi B", "Invasion of Privacy", "feminino"],
    "HUMBLE": ["rap", "2017", "eeuu", "confiado", "motivacion", "Kendrick Lamar", "DAMN.", "premio pulitzer"],
    "Money Trees": ["rap", "2012", "eeuu", "reflexivo", "nostalgia", "Kendrick Lamar", "good kid, m.A.A.d city", "narrativo"],
    "No Role Modelz": ["rap", "2014", "eeuu", "critico", "reflexion", "J. Cole", "2014 Forest Hills Drive", "consciente"],
    "Panda": ["rap", "2016", "eeuu", "minimalista", "fiesta", "Desiigner", "New English", "viral"],
    "The Girl from Ipanema": ["bossa nova", "1964", "brasil", "seductor", "relajacion", "Stan Getz", "João Gilberto", "standard"],
    "Corcovado": ["bossa nova", "1960", "brasil", "tranquilo", "relajacion", "Antônio Carlos Jobim", "The Composer of Desafinado, Plays", "clasico"],
    "Desafinado": ["bossa nova", "1959", "brasil", "ironico", "romantico", "João Gilberto", "Chega de Saudade", "fundacional"],
    "Waters of March": ["bossa nova", "1972", "brasil", "poetico", "reflexion", "Antônio Carlos Jobim", "Jobim", "masterpiece"],
    "Blue in Green": ["jazz", "1959", "eeuu", "melancolico", "meditacion", "Miles Davis", "Kind of Blue", "modal"],
    "My Favorite Things": ["jazz", "1961", "eeuu", "alegre", "concierto", "John Coltrane", "My Favorite Things", "experimental"],
    "Spain": ["jazz", "1972", "eeuu", "virtuosico", "concierto", "Chick Corea", "Light as a Feather", "fusion"],
    "Cantaloupe Island": ["jazz", "1964", "eeuu", "groove", "relajacion", "Herbie Hancock", "Empyrean Isles", "funky"],
    "Song for My Father": ["jazz", "1964", "eeuu", "nostalgico", "reflexion", "Horace Silver", "Song for My Father", "hard bop"],
    "Mercy, Mercy, Mercy": ["jazz", "1966", "eeuu", "gospel", "fiesta", "Cannonball Adderley", "Mercy, Mercy, Mercy!", "soul jazz"],
    "Symphony No. 9": ["clasica", "1824", "alemania", "triunfal", "coro", "Ludwig van Beethoven", "Symphony No. 9", "himno alegria"],
    "The Four Seasons": ["clasica", "1723", "italia", "descriptivo", "concierto", "Antonio Vivaldi", "Il cimento dell'armonia e dell'inventione", "programatico"],
    "Clair de Lune": ["clasica", "1905", "francia", "onirico", "relajacion", "Claude Debussy", "Suite Bergamasque", "impresionista"],
    "Canon in D": ["clasica", "1680", "alemania", "armonioso", "ceremonia", "Johann Pachelbel", "Canon and Gigue", "popular"],
    "Moonlight Sonata": ["clasica", "1801", "alemania", "melancolico", "reflexion", "Ludwig van Beethoven", "Piano Sonata No. 14", "clasico"],
    "The Blue Danube": ["clasica", "1866", "austria", "elegante", "baile", "Johann Strauss II", "The Blue Danube", "vals"],
    "Boléro": ["clasica", "1928", "francia", "obsesivo", "dramatico", "Maurice Ravel", "Boléro", "minimalista"],
    "Eine kleine Nachtmusik": ["clasica", "1787", "austria", "alegre", "entretenimiento", "Wolfgang Amadeus Mozart", "Serenade No. 13", "clasico"],
    "Toccata and Fugue": ["clasica", "1704", "alemania", "dramatico", "organo", "Johann Sebastian Bach", "Toccata and Fugue", "barroco"],
    "Rhapsody in Blue": ["clasica", "1924", "eeuu", "energico", "concierto", "George Gershwin", "Rhapsody in Blue", "jazz-classical"],
    "The Dance": ["country", "1990", "eeuu", "melancolico", "reflexion", "Garth Brooks", "Garth Brooks", "filosofico"],
    "Live Like You Were Dying": ["country", "2004", "eeuu", "inspirador", "motivacion", "Tim McGraw", "Live Like You Were Dying", "superacion"],
    "Before He Cheats": ["country", "2005", "eeuu", "vengativo", "desahogo", "Carrie Underwood", "Some Hearts", "empoderamiento"],
    "Die a Happy Man": ["country", "2015", "eeuu", "romantico", "intimo", "Thomas Rhett", "Tangled Up", "sentimental"],
    "Body Like a Back Road": ["country", "2017", "eeuu", "playero", "conduccion", "Sam Hunt", "Body Like a Back Road", "pop country"],
    "Tennessee Whiskey": ["country", "2015", "eeuu", "sensual", "romantico", "Chris Stapleton", "Traveller", "soul"],
    "Cruise": ["country", "2012", "eeuu", "festivo", "fiesta", "Florida Georgia Line", "Here's to the Good Times", "bro-country"],
    "Springsteen": ["country", "2012", "eeuu", "nostalgico", "memoria", "Eric Church", "Chief", "rockero"],
    "Humble and Kind": ["country", "2016", "eeuu", "reflexivo", "consejo", "Tim McGraw", "Damn Country Music", "familiar"],
    "Blue Ain't Your Color": ["country", "2016", "eeuu", "melancolico", "consuelo", "Keith Urban", "Ripcord", "bluesy"],
    "Baila Morena": ["lambada", "1989", "brasil", "festivo", "bailable", "Luiz Caldas", "Lambada", "exito"],
    "Zombie": ["rock", "1994", "irlanda", "protesta", "reflexion", "The Cranberries", "No Need to Argue", "politico"],
    "Moscow": ["pop", "2000", "rusia", "nostalgico", "fiesta", "T.A.T.u.", "200 km/h in the Wrong Lane", "controversial"],
    "Nkosi Sikelel' iAfrika": ["himno", "1897", "sudafrica", "solemne", "ceremonia", "Enoch Sontonga", "Himno Nacional", "patriotico"],
    "Malaika": ["folk", "1960", "tanzania", "romantico", "melancolico", "Miriam Makeba", "Miriam Makeba", "swahili"],
    "Smooth Operator": ["r&b", "1984", "reino unido", "seductor", "bailable", "Sade", "Diamond Life", "elegante"],
    "Mas Que Nada": ["samba", "1963", "brasil", "festivo", "bailable", "Sérgio Mendes", "Brasil '66", "exito"],
    "The Girl from Ipanema": ["bossa nova", "1964", "brasil", "seductor", "relajacion", "Antônio Carlos Jobim", "Getz/Gilberto", "standard"],
    "Aquarela do Brasil": ["samba", "1939", "brasil", "patriotico", "nostalgico", "Ary Barroso", "Brasil", "himno"],
    "Cucurrucucú Paloma": ["folk", "1954", "mexico", "triste", "melancolico", "Lola Beltrán", "Cucurrucucú", "eterno"],
    "Sabor a Mí": ["bolero", "1959", "mexico", "intimo", "romantico", "Alvaro Carrillo", "Eternamente", "clasico"],
    "La Barca": ["bolero", "1962", "mexico", "melancolico", "despedida", "Luis Miguel", "Romance", "version"],
    "Somos Novios": ["bolero", "1968", "mexico", "romantico", "intimo", "Armando Manzanero", "Somos Novios", "standard"],
    "Contigo Aprendí": ["bolero", "1968", "mexico", "agradecido", "romantico", "Armando Manzanero", "Contigo Aprendí", "clasico"],
    "El Reloj": ["bolero", "1956", "mexico", "angustiado", "romantico", "Lucho Gatica", "El Reloj", "dramatico"],
    "Gavilán o Paloma": ["bolero", "1977", "mexico", "dramatico", "desamor", "José José", "Reencuentro", "iconico"],
    "Abrázame Muy Fuerte": ["bolero", "2000", "mexico", "pasional", "romantico", "Juan Gabriel", "Abrázame Muy Fuerte", "moderno"],
    "Querida": ["balada", "1984", "mexico", "nostalgico", "romantico", "Juan Gabriel", "Querida", "exito"],
    "Hasta Que Te Conocí": ["balada", "1996", "mexico", "revelador", "desahogo", "Juan Gabriel", "El México Que Se Nos Fue", "autobiografico"],
    "Secreto de Amor": ["balada", "1999", "puerto rico", "romantico", "confesion", "Joan Sebastian", "Secreto de Amor", "popular"],
    "Dog Days Are Over": ["indie", "2008", "reino unido", "euforico", "liberacion", "Florence + The Machine", "Lungs", "himno"],
    "Little Talks": ["indie", "2011", "islandia", "dialogo", "melancolico", "Of Monsters and Men", "My Head Is an Animal", "narrativo"],
    "Pumped Up Kicks": ["indie", "2010", "eeuu", "oscurio", "ironico", "Foster the People", "Torches", "controversial"],
    "Ho Hey": ["indie", "2012", "eeuu", "alegre", "romantico", "The Lumineers", "The Lumineers", "folk indie"],
    "Riptide": ["indie", "2013", "australia", "nostalgico", "acustico", "Vance Joy", "Dream Your Life Away", "ukulele"],
    "Take Me to Church": ["indie", "2013", "irlanda", "critico", "pasional", "Hozier", "Hozier", "social"],
    "Budapest": ["indie", "2014", "reino unido", "romantico", "acustico", "George Ezra", "Wanted on Voyage", "simple"],
    "Shut Up and Dance": ["indie", "2014", "eeuu", "euforico", "baile", "WALK THE MOON", "Talking Is Hard", "80s"],
    "Feel It Still": ["indie", "2017", "eeuu", "funk", "bailable", "Portugal. The Man", "Woodstock", "retro"],
    "Electric Feel": ["indie", "2007", "eeuu", "sensual", "baile", "MGMT", "Oracular Spectacular", "psicodelico"],
    "Dynamite": ["k-pop", "2020", "corea del sur", "alegre", "baile", "BTS", "Dynamite", "ingles"],
    "Butter": ["k-pop", "2021", "corea del sur", "fresco", "baile", "BTS", "Butter", "veraniego"],
    "How You Like That": ["k-pop", "2020", "corea del sur", "poderoso", "baile", "BLACKPINK", "The Album", "empoderamiento"],
    "Kill This Love": ["k-pop", "2019", "corea del sur", "intenso", "baile", "BLACKPINK", "Kill This Love", "dramatico"],
    "Gangnam Style": ["k-pop", "2012", "corea del sur", "humoristico", "baile", "PSY", "PSY 6甲", "fenomeno viral"],
    "Sukiyaki": ["j-pop", "1961", "japon", "melancolico", "romantico", "Kyu Sakamoto", "Sukiyaki", "internacional"],
    "Lemon": ["j-pop", "2018", "japon", "triste", "reflexion", "Kenshi Yonezu", "Lemon", "moderno"],
    "Gurenge": ["j-pop", "2019", "japon", "epico", "anime", "LiSA", "Gurenge", "demon slayer"],
    "Paprika": ["j-pop", "2020", "japon", "alegre", "infantil", "Foorin", "Paprika", "juegos olimpicos"],
    "Pretender": ["j-pop", "2019", "japon", "dramatico", "romantico", "Official HIGE DANdism", "Traveler", "exito"],
    "Oceans (Where Feet May Fail)": ["cristiana", "2013", "australia", "devocional", "meditacion", "Hillsong UNITED", "Zion", "adoracion"],
    "What a Beautiful Name": ["cristiana", "2016", "australia", "glorioso", "adoracion", "Hillsong Worship", "Let There Be Light", "premio grammy"],
    "10,000 Reasons (Bless the Lord)": ["cristiana", "2011", "reino unido", "agradecido", "adoracion", "Matt Redman", "10,000 Reasons", "himno"],
    "Amazing Grace": ["gospel", "1779", "reino unido", "redencion", "adoracion", "John Newton", "Amazing Grace", "historico"],
    "Oh Happy Day": ["gospel", "1967", "eeuu", "alegre", "celebración", "Edwin Hawkins Singers", "Oh Happy Day", "clasico"],
    "I Can Only Imagine": ["cristiana", "1999", "eeuu", "esperanzador", "reflexion", "MercyMe", "The Worship Project", "exito"],
    "How Great Thou Art": ["gospel", "1885", "suecia", "majestuoso", "adoracion", "Carl Boberg", "How Great Thou Art", "himno"],
    "Shout to the Lord": ["cristiana", "1993", "australia", "poderoso", "adoracion", "Darlene Zschech", "Shout to the Lord", "moderno"],
    "Reckless Love": ["cristiana", "2017", "eeuu", "devocional", "adoracion", "Cory Asbury", "Reckless Love", "intimo"],
    "Who You Say I Am": ["cristiana", "2018", "australia", "identidad", "adoracion", "Hillsong Worship", "There Is More", "empoderamiento"],
    "Baby Shark": ["infantil", "2016", "corea del sur", "repetitivo", "educativo", "Pinkfong", "Baby Shark", "viral"],
    "Canticos": ["infantil", "2017", "eeuu", "bilingue", "educativo", "Canticos", "Canticos", "latino"],
    "Un Poco Loco": ["infantil", "2017", "eeuu", "alegre", "pelicula", "Anthony Gonzalez", "Coco", "disney"],
    "Remember Me": ["infantil", "2017", "eeuu", "emocional", "pelicula", "Gael García Bernal", "Coco", "familia"],
    "Let It Go": ["infantil", "2013", "eeuu", "empoderado", "pelicula", "Idina Menzel", "Frozen", "disney"],
    "Hakuna Matata": ["infantil", "1994", "eeuu", "alegre", "pelicula", "Nathan Lane", "The Lion King", "filosofia"],
    "Under the Sea": ["infantil", "1989", "eeuu", "festivo", "pelicula", "Samuel E. Wright", "The Little Mermaid", "caribeño"],
    "You've Got a Friend in Me": ["infantil", "1995", "eeuu", "amistad", "pelicula", "Randy Newman", "Toy Story", "amistad"],
    "Colors of the Wind": ["infantil", "1995", "eeuu", "ecologico", "pelicula", "Judy Kuhn", "Pocahontas", "naturaleza"],
    "A Whole New World": ["infantil", "1992", "eeuu", "romantico", "pelicula", "Lea Salonga", "Aladdin", "fantasia"]
}
# Categorías fijas (vacías)
categorias={
    "Género Musical": set(),
    "Época o Periodo Histórico": set(),
    "Contexto Cultural y Geográfico": set(),
    "Características Estéticas o de Estado de Ánimo": set(),
    "Función o Contexto de Uso": set(),
    "otros": set()
}
# Perfiles
pesos_base={
    "Género Musical": 0.25,
    "Época o Periodo Histórico": 0.20,
    "Contexto Cultural y Geográfico": 0.15,
    "Características Estéticas o de Estado de Ánimo": 0.15,
    "Función o Contexto de Uso": 0.15,
    "otros": 0.10
}
perfiles={
    "emocional": {
        "Género Musical": 0.20,
        "Época o Periodo Histórico": 0.15,
        "Contexto Cultural y Geográfico": 0.10,
        "Características Estéticas o de Estado de Ánimo": 0.25,
        "Función o Contexto de Uso": 0.15,
        "otros": 0.15
    },
    "artista": {
        "Género Musical": 0.30,
        "Época o Periodo Histórico": 0.20,
        "Contexto Cultural y Geográfico": 0.15,
        "Características Estéticas o de Estado de Ánimo": 0.10,
        "Función o Contexto de Uso": 0.10,
        "otros": 0.15
    },
    "fiesta": {
        "Género Musical": 0.25,
        "Época o Periodo Histórico": 0.10,
        "Contexto Cultural y Geográfico": 0.10,
        "Características Estéticas o de Estado de Ánimo": 0.10,
        "Función o Contexto de Uso": 0.30,
        "otros": 0.15
    }
}
# Clasificación por posición
def clasificar_etiquetas(canciones):
    for categoria in categorias:
        categorias[categoria]=set()
    mapeo_posiciones={
        0: "Género Musical",
        1: "Época o Periodo Histórico",
        2: "Contexto Cultural y Geográfico",
        3: "Características Estéticas o de Estado de Ánimo",
        4: "Función o Contexto de Uso"
    }
    for etiquetas in canciones.values():
        for posicion,categoria in mapeo_posiciones.items():
            if posicion<len(etiquetas):
                categorias[categoria].add(etiquetas[posicion])
        if len(etiquetas)>5:
            for etiqueta_extra in etiquetas[5:]:
                categorias["otros"].add(etiqueta_extra)
clasificar_etiquetas(canciones)
# Cálculo de pesos etiqueta
def peso_etiqueta(etiqueta, perfil, etiquetas_comunes_otros):
    for categoria, etiquetas_cat in categorias.items():
        if etiqueta in etiquetas_cat:
            peso_categoria=perfiles[perfil].get(categoria, pesos_base[categoria])
            if categoria=="otros":
                    num_comunes_otros=max(1,len(etiquetas_comunes_otros))
                    return peso_categoria/num_comunes_otros
            else:
                return peso_categoria
def jaccard_ponderado(a,b,perfil):
    set_a=set(a)
    set_b=set(b) 
    inter=set_a&set_b
    union=set_a|set_b
    otros_inter=inter&categorias["otros"]
    otros_union=union&categorias["otros"]
    num=sum(peso_etiqueta(x,perfil,otros_inter) for x in inter)
    den=sum(peso_etiqueta(x,perfil,otros_union) for x in union)
    return num/den,inter
def ordenar(lista):
    n=len(lista)
    for i in range(n):
        intercambiado=False
        for j in range(0,n-i-1):
            if lista[j][1]<lista[j+1][1]:
                lista[j],lista[j+1]=lista[j+1],lista[j]
                intercambiado=True
        if not intercambiado:
            break
    return lista
# Búsqueda principal
def buscar(consulta, perfil="emocional", n=100):
    etiquetas_consulta=canciones.get(consulta)
    resultados=[]
    for titulo,etiquetas_cancion in canciones.items():
        indice,comunes=jaccard_ponderado(etiquetas_consulta,etiquetas_cancion,perfil)
        resultados.append((titulo,indice,comunes))
    resultados=ordenar(resultados)
    return resultados[:n]
# Estadísticas
def mostrar_estadisticas():
    total_etiquetas=sum(len(etiquetas) for etiquetas in canciones.values())
    total_etiquetas_unicas=len(set().union(*[set(etiquetas) for etiquetas in canciones.values()]))
    print(f"Total de canciones: {len(canciones)}")
    print(f"Total de etiquetas: {total_etiquetas}")
    print(f"Etiquetas únicas: {total_etiquetas_unicas}")
    print(f"Etiquetas por canción: {total_etiquetas/len(canciones):.1f}")
    print("\nDistribución por categorías:")
    for categoria, etiquetas in categorias.items():
        print(f"  {categoria}: {len(etiquetas)} etiquetas")
    print(f"\nPerfiles disponibles: {', '.join(perfiles.keys())}")
# Menú
def mostrar_menu():
    print("Motor de búsqueda de canciones")
    print("Perfiles disponibles:", ", ".join(perfiles.keys()))
    print("\nCanciones disponibles:")
    for i, cancion in enumerate(canciones.keys(),1):
        print(f"{i}.{cancion}")
# Programa principal
mostrar_menu()
mostrar_estadisticas()
while True:
    consulta=input("\nIngrese canción o 'salir' para terminar: ").strip() 
    if consulta.lower()=='salir':
        print("Chao")
        break
    perfil=input("Ingrese perfil (emocional/artista/fiesta) [emocional]: ").strip().lower()
    if not perfil:
        perfil="emocional"
    resultados=buscar(consulta, perfil)
    print(f"\nResultados para'{consulta}'(perfil:{perfil}):")
    for i, (titulo,indice,comunes) in enumerate(resultados, 1):
        print(f"{i}.{titulo}—similitud:{indice}")
        if comunes:
            print(f"Etiquetas comunes:{comunes}")
        print()